/* This file was generated by the Hex-Rays decompiler version 7.7.0.220118.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

// void *__cdecl memmove(void *Dst, const void *Src, size_t MaxCount);
// void *__cdecl memset(void *Dst, int Val, size_t Size);
NTSTATUS __fastcall sub_1400014E0(__int64 a1, IRP *a2, _BYTE *a3);
NTSTATUS __fastcall sub_140001504(__int64 a1, IRP *a2, _BYTE *a3);
NTSTATUS __fastcall sub_140001528(__int64 a1, IRP *a2, _BYTE *a3);
NTSTATUS __fastcall sub_14000154C(__int64 a1, IRP *a2, _BYTE *a3);
NTSTATUS __fastcall sub_140001570(struct _DEVICE_OBJECT *a1, IRP *a2, DWORD a3);
__int64 __fastcall sub_1400015B0(__int64 a1, _QWORD *a2);
__int64 __fastcall sub_140001604(__int64 a1, _QWORD *a2);
__int64 __fastcall sub_1400016A4(__int64 a1, __int64 a2);
__int64 __fastcall sub_1400016F8(__int64, IRP *);
PVOID __fastcall sub_140001870(size_t Size);
// void __stdcall ExFreePool(PVOID P);
__int64 __fastcall sub_1400018BC(__int64 a1, __int64 a2, struct _KEVENT *a3);
NTSTATUS __fastcall sub_1400018DC(__int64 a1, IRP *a2);
NTSTATUS __fastcall sub_14000191C(__int64 a1, IRP *a2);
bool __fastcall sub_140001938(char a1, _WORD *a2, const WCHAR *a3, int *a4);
// NTSTATUS __stdcall HidRegisterMinidriver(PHID_MINIDRIVER_REGISTRATION MinidriverRegistration);
void sub_140005000();
int *__fastcall sub_140005008(__int64 a1);
__int64 __fastcall sub_140005028(__int64, __int64);
__int64 __fastcall nullsub_1(); // weak
NTSTATUS __fastcall sub_140005050(__int64 a1);
NTSTATUS __fastcall sub_140005084(PDEVICE_OBJECT DeviceObject, ULONG IoControlCode, PVOID InputBuffer, ULONG InputBufferLength, PVOID OutputBuffer, ULONG OutputBufferLength, BOOLEAN InternalDeviceIoControl);
__int64 __fastcall sub_140005154(__int64 a1);
NTSTATUS __fastcall sub_140005180(__int64 a1);
__int64 __fastcall sub_140005264(__int64 a1, IRP *a2);
__int64 __fastcall sub_14000535C(__int64 a1);
__int64 __fastcall sub_140005398(PDEVICE_OBJECT DeviceObject, PIRP Irp); // idb
NTSTATUS __fastcall sub_140005438(__int64 a1);
__int64 __fastcall sub_1400054A0(__int64 a1);
NTSTATUS __stdcall DriverEntry(_DRIVER_OBJECT *DriverObject, PUNICODE_STRING RegistryPath);
char sub_1400060D8();

//-------------------------------------------------------------------------
// Data declarations

// extern PIRP (__stdcall *IoBuildDeviceIoControlRequest)(ULONG IoControlCode, PDEVICE_OBJECT DeviceObject, PVOID InputBuffer, ULONG InputBufferLength, PVOID OutputBuffer, ULONG OutputBufferLength, BOOLEAN InternalDeviceIoControl, PKEVENT Event, PIO_STATUS_BLOCK IoStatusBlock);
// extern NTSTATUS (__stdcall *IofCallDriver)(PDEVICE_OBJECT DeviceObject, PIRP Irp);
// extern void (__stdcall *IofCompleteRequest)(PIRP Irp, CCHAR PriorityBoost);
// extern PVOID (__stdcall *ExAllocatePoolWithTag)(POOL_TYPE PoolType, SIZE_T NumberOfBytes, ULONG Tag);
// extern LONG (__stdcall *KeSetEvent)(PRKEVENT Event, KPRIORITY Increment, BOOLEAN Wait);
// extern NTSTATUS (__stdcall *PoCallDriver)(PDEVICE_OBJECT DeviceObject, PIRP Irp);
// extern void (__stdcall *PoStartNextPowerIrp)(PIRP Irp);
// extern NTSTATUS (__stdcall *KeWaitForSingleObject)(PVOID Object, KWAIT_REASON WaitReason, KPROCESSOR_MODE WaitMode, BOOLEAN Alertable, PLARGE_INTEGER Timeout);
// extern void (__stdcall *KeInitializeEvent)(PRKEVENT Event, EVENT_TYPE Type, BOOLEAN State);
// extern NTSTATUS (__stdcall *RtlQueryRegistryValues)(ULONG RelativeTo, PCWSTR Path, PRTL_QUERY_REGISTRY_TABLE QueryTable, PVOID Context, PVOID Environment);
int dword_140003040 = 0; // weak
__int64 qword_140003050 = 0i64; // weak
int dword_14000306C = 0; // weak


//----- (00000001400014E0) ----------------------------------------------------
NTSTATUS __fastcall sub_1400014E0(__int64 a1, IRP *a2, _BYTE *a3)
{
  struct _DEVICE_OBJECT *v3; // rcx

  v3 = *(struct _DEVICE_OBJECT **)(*(_QWORD *)(a1 + 64) + 8i64);
  if ( !v3 )
    return -1073741810;
  *a3 = 0;
  return sub_140001570(v3, a2, 0x2A202Fu);
}

//----- (0000000140001504) ----------------------------------------------------
NTSTATUS __fastcall sub_140001504(__int64 a1, IRP *a2, _BYTE *a3)
{
  struct _DEVICE_OBJECT *v3; // rcx

  v3 = *(struct _DEVICE_OBJECT **)(*(_QWORD *)(a1 + 64) + 8i64);
  if ( !v3 )
    return -1073741810;
  *a3 = 0;
  return sub_140001570(v3, a2, 0x2A2037u);
}

//----- (0000000140001528) ----------------------------------------------------
NTSTATUS __fastcall sub_140001528(__int64 a1, IRP *a2, _BYTE *a3)
{
  struct _DEVICE_OBJECT *v3; // rcx

  v3 = *(struct _DEVICE_OBJECT **)(*(_QWORD *)(a1 + 64) + 8i64);
  if ( !v3 )
    return -1073741810;
  *a3 = 0;
  return sub_140001570(v3, a2, 0x2A2033u);
}

//----- (000000014000154C) ----------------------------------------------------
NTSTATUS __fastcall sub_14000154C(__int64 a1, IRP *a2, _BYTE *a3)
{
  struct _DEVICE_OBJECT *v3; // rcx

  v3 = *(struct _DEVICE_OBJECT **)(*(_QWORD *)(a1 + 64) + 8i64);
  if ( !v3 )
    return -1073741810;
  *a3 = 0;
  return sub_140001570(v3, a2, 0x2A203Bu);
}

//----- (0000000140001570) ----------------------------------------------------
NTSTATUS __fastcall sub_140001570(struct _DEVICE_OBJECT *a1, IRP *a2, DWORD a3)
{
  struct _IO_STACK_LOCATION *CurrentStackLocation; // rax

  CurrentStackLocation = a2->Tail.Overlay.CurrentStackLocation;
  *(_OWORD *)&CurrentStackLocation[-1].MajorFunction = *(_OWORD *)&CurrentStackLocation->MajorFunction;
  *(_OWORD *)&CurrentStackLocation[-1].Parameters.NotifyDirectoryEx.CompletionFilter = *(_OWORD *)&CurrentStackLocation->Parameters.NotifyDirectoryEx.CompletionFilter;
  *(_OWORD *)(&CurrentStackLocation[-1].Parameters.SetQuota + 6) = *(_OWORD *)(&CurrentStackLocation->Parameters.SetQuota
                                                                             + 6);
  CurrentStackLocation[-1].FileObject = CurrentStackLocation->FileObject;
  CurrentStackLocation[-1].Control = 0;
  a2->Tail.Overlay.CurrentStackLocation[-1].Parameters.Read.ByteOffset.LowPart = a3;
  return IofCallDriver(a1, a2);
}

//----- (00000001400015B0) ----------------------------------------------------
__int64 __fastcall sub_1400015B0(__int64 a1, _QWORD *a2)
{
  __int64 v2; // r9
  __int64 result; // rax
  __int16 v5; // dx

  v2 = a2[14];
  if ( *(_DWORD *)(a2[23] + 8i64) >= 9u )
  {
    result = 0i64;
    v5 = *(_WORD *)(*(_QWORD *)(*(_QWORD *)(a1 + 64) + 16i64) + 16i64);
    *(_QWORD *)v2 = 0i64;
    *(_DWORD *)v2 = 73993;
    *(_WORD *)(v2 + 4) = 256;
    *(_BYTE *)(v2 + 6) = 34;
    *(_WORD *)(v2 + 7) = v5;
    a2[7] = 9i64;
  }
  else
  {
    result = 3221225507i64;
    a2[7] = 0i64;
  }
  return result;
}

//----- (0000000140001604) ----------------------------------------------------
__int64 __fastcall sub_140001604(__int64 a1, _QWORD *a2)
{
  unsigned int v2; // edi
  _WORD *v4; // rbx
  _WORD *v5; // rbp
  __int16 v6; // ax

  v2 = 0;
  if ( *(_DWORD *)(a2[23] + 8i64) >= 0x20u )
  {
    v4 = (_WORD *)a2[14];
    v5 = *(_WORD **)(*(_QWORD *)(a1 + 64) + 16i64);
    memset(v4, 0, 0x20ui64);
    a2[7] = 32i64;
    *(_DWORD *)v4 = 32;
    v4[2] = v5[2];
    v6 = v5[4];
    v4[3] = v6;
    if ( (unsigned __int16)(v6 + 15704) <= 2u )
      v4[4] = v5[6];
    else
      v4[4] = 1;
  }
  else
  {
    return (unsigned int)-1073741789;
  }
  return v2;
}

//----- (00000001400016A4) ----------------------------------------------------
__int64 __fastcall sub_1400016A4(__int64 a1, __int64 a2)
{
  __int64 v3; // rdx
  unsigned __int16 v4; // cx
  __int64 v6; // rbx

  v3 = *(_QWORD *)(*(_QWORD *)(a1 + 64) + 16i64);
  v4 = *(_WORD *)(v3 + 16);
  if ( v4 > *(_WORD *)(*(_QWORD *)(a2 + 184) + 8i64) )
    return 3221225507i64;
  v6 = v4;
  memmove(*(void **)(a2 + 112), *(const void **)(v3 + 24), v4);
  *(_QWORD *)(a2 + 56) = v6;
  return 0i64;
}

//----- (00000001400016F8) ----------------------------------------------------
__int64 __fastcall sub_1400016F8(__int64 a1, IRP *a2)
{
  struct _IO_STACK_LOCATION *CurrentStackLocation; // r8
  __int64 v4; // rdx
  unsigned int v5; // ebx
  unsigned int LowPart; // eax
  unsigned int v7; // eax
  unsigned int v8; // eax
  unsigned int v9; // eax
  unsigned int v10; // eax
  unsigned int v11; // eax
  struct _DEVICE_OBJECT *v12; // rcx
  DWORD v13; // r8d
  unsigned int v14; // eax
  unsigned int v15; // eax
  unsigned int v16; // eax
  unsigned int v17; // eax
  unsigned int v18; // eax
  char v20; // [rsp+30h] [rbp+8h] BYREF

  CurrentStackLocation = a2->Tail.Overlay.CurrentStackLocation;
  v20 = 1;
  v4 = *(_QWORD *)(a1 + 64);
  if ( *(_BYTE *)(*(_QWORD *)(v4 + 16) + 40i64) != 2 )
  {
    a2->IoStatus.Information = 0i64;
    v5 = -1073741661;
LABEL_36:
    a2->IoStatus.Status = v5;
    IofCompleteRequest(a2, 0);
    return v5;
  }
  LowPart = CurrentStackLocation->Parameters.Read.ByteOffset.LowPart;
  if ( LowPart > 0xB0023 )
  {
    v15 = LowPart - 720935;
    if ( v15 )
    {
      v16 = v15 - 362;
      if ( v16 )
      {
        v17 = v16 - 1;
        if ( v17 )
        {
          v18 = v17 - 3;
          if ( v18 )
          {
            if ( v18 != 13 )
              goto LABEL_29;
            v14 = sub_140001504(a1, a2, &v20);
          }
          else
          {
            v14 = sub_14000154C(a1, a2, &v20);
          }
        }
        else
        {
          v14 = sub_1400014E0(a1, a2, &v20);
        }
      }
      else
      {
        v14 = sub_140001528(a1, a2, &v20);
      }
    }
    else
    {
      v14 = sub_140001604(a1, a2);
    }
  }
  else
  {
    if ( LowPart == 720931 )
    {
LABEL_11:
      v5 = 0;
      goto LABEL_36;
    }
    v7 = LowPart - 720899;
    if ( v7 )
    {
      v8 = v7 - 4;
      if ( v8 )
      {
        v9 = v8 - 4;
        if ( v9 )
        {
          v10 = v9 - 4;
          if ( v10 )
          {
            v11 = v10 - 4;
            if ( !v11 )
            {
              v5 = 0;
              if ( a2->UserBuffer && CurrentStackLocation->Parameters.Create.Options )
                a2->IoStatus.Information = 0i64;
              else
                v5 = -1073741592;
              goto LABEL_36;
            }
            if ( v11 == 12 )
              goto LABEL_11;
LABEL_29:
            v5 = -1073741637;
            goto LABEL_36;
          }
          v12 = *(struct _DEVICE_OBJECT **)(v4 + 8);
          if ( !v12 )
          {
LABEL_17:
            v5 = -1073741810;
            goto LABEL_36;
          }
          v13 = 2760743;
        }
        else
        {
          v12 = *(struct _DEVICE_OBJECT **)(v4 + 8);
          if ( !v12 )
            goto LABEL_17;
          v13 = 2760739;
        }
        v20 = 0;
        v14 = sub_140001570(v12, a2, v13);
      }
      else
      {
        v14 = sub_1400016A4(a1, (__int64)a2);
      }
    }
    else
    {
      v14 = sub_1400015B0(a1, a2);
    }
  }
  v5 = v14;
  if ( v20 )
    goto LABEL_36;
  return v5;
}

//----- (0000000140001870) ----------------------------------------------------
PVOID __fastcall sub_140001870(size_t Size)
{
  unsigned int v1; // edi
  PVOID PoolWithTag; // rax
  PVOID v3; // rbx

  v1 = Size;
  PoolWithTag = ExAllocatePoolWithTag((POOL_TYPE)512, (unsigned int)Size, 0x594F4A4Cu);
  v3 = PoolWithTag;
  if ( PoolWithTag )
    memset(PoolWithTag, 0, v1);
  return v3;
}

//----- (00000001400018BC) ----------------------------------------------------
__int64 __fastcall sub_1400018BC(__int64 a1, __int64 a2, struct _KEVENT *a3)
{
  KeSetEvent(a3, 1, 0);
  return 3221225494i64;
}

//----- (00000001400018DC) ----------------------------------------------------
NTSTATUS __fastcall sub_1400018DC(__int64 a1, IRP *a2)
{
  PoStartNextPowerIrp(a2);
  ++a2->CurrentLocation;
  ++a2->Tail.Overlay.CurrentStackLocation;
  return PoCallDriver(*(PDEVICE_OBJECT *)(*(_QWORD *)(a1 + 64) + 8i64), a2);
}

//----- (000000014000191C) ----------------------------------------------------
NTSTATUS __fastcall sub_14000191C(__int64 a1, IRP *a2)
{
  struct _DEVICE_OBJECT *v2; // rcx

  v2 = *(struct _DEVICE_OBJECT **)(*(_QWORD *)(a1 + 64) + 8i64);
  ++a2->CurrentLocation;
  ++a2->Tail.Overlay.CurrentStackLocation;
  return IofCallDriver(v2, a2);
}

//----- (0000000140001938) ----------------------------------------------------
bool __fastcall sub_140001938(char a1, _WORD *a2, const WCHAR *a3, int *a4)
{
  __int64 v8; // r8
  ULONG v9; // ecx
  int v11; // [rsp+38h] [rbp-D0h] BYREF
  struct _RTL_QUERY_REGISTRY_TABLE QueryTable[2]; // [rsp+48h] [rbp-C0h] BYREF
  WCHAR Path[256]; // [rsp+B8h] [rbp-50h] BYREF

  v11 = *a4;
  memset(Path, 0, sizeof(Path));
  v8 = -1i64;
  do
    ++v8;
  while ( a2[v8] );
  memmove(Path, a2, 2 * v8);
  memset(QueryTable, 0, sizeof(QueryTable));
  QueryTable[0].DefaultType = 4;
  QueryTable[0].DefaultLength = 4;
  QueryTable[0].DefaultData = &v11;
  QueryTable[0].Flags = 32;
  QueryTable[0].Name = a3;
  QueryTable[0].EntryContext = a4;
  v9 = -2147483647;
  if ( a1 )
    v9 = 0x80000000;
  return RtlQueryRegistryValues(v9, Path, QueryTable, 0i64, 0i64) >= 0;
}

//----- (0000000140005000) ----------------------------------------------------
void sub_140005000()
{
  --dword_14000306C;
}
// 14000306C: using guessed type int dword_14000306C;

//----- (0000000140005008) ----------------------------------------------------
int *__fastcall sub_140005008(__int64 a1)
{
  __int64 v1; // rcx
  int *result; // rax

  v1 = *(_QWORD *)(*(_QWORD *)(a1 + 64) + 16i64);
  result = &dword_140003040;
  *(_QWORD *)(v1 + 32) = &dword_140003040;
  *(_DWORD *)v1 = 5064008;
  *(_BYTE *)(v1 + 40) = 0;
  return result;
}
// 140003040: using guessed type int dword_140003040;

//----- (0000000140005028) ----------------------------------------------------
__int64 __fastcall sub_140005028(__int64 a1, __int64 a2)
{
  if ( ++dword_14000306C == 1 )
    qword_140003048 = a1;
  *(_DWORD *)(a2 + 48) &= ~0x80u;
  return 0i64;
}
// 140003048: using guessed type __int64 qword_140003048;
// 14000306C: using guessed type int dword_14000306C;

//----- (0000000140005050) ----------------------------------------------------
NTSTATUS __fastcall sub_140005050(__int64 a1)
{
  return sub_140005084(*(PDEVICE_OBJECT *)(*(_QWORD *)(a1 + 64) + 8i64), 0x2A201Cu, 0i64, 0, 0i64, 0, 1u);
}

//----- (0000000140005084) ----------------------------------------------------
NTSTATUS __fastcall sub_140005084(
        PDEVICE_OBJECT DeviceObject,
        ULONG IoControlCode,
        PVOID InputBuffer,
        ULONG InputBufferLength,
        PVOID OutputBuffer,
        ULONG OutputBufferLength,
        BOOLEAN InternalDeviceIoControl)
{
  IRP *v11; // rax
  NTSTATUS result; // eax
  struct _IO_STATUS_BLOCK IoStatusBlock; // [rsp+50h] [rbp-38h] BYREF
  struct _KEVENT Object; // [rsp+60h] [rbp-28h] BYREF

  KeInitializeEvent(&Object, NotificationEvent, 0);
  v11 = IoBuildDeviceIoControlRequest(
          IoControlCode,
          DeviceObject,
          InputBuffer,
          InputBufferLength,
          OutputBuffer,
          OutputBufferLength,
          InternalDeviceIoControl,
          &Object,
          &IoStatusBlock);
  if ( !v11 )
    return -1073741670;
  result = IofCallDriver(DeviceObject, v11);
  if ( result == 259 )
  {
    KeWaitForSingleObject(&Object, Suspended, 0, 0, 0i64);
    return IoStatusBlock.Status;
  }
  return result;
}

//----- (0000000140005154) ----------------------------------------------------
__int64 __fastcall sub_140005154(__int64 a1)
{
  __int64 v1; // rbx
  void *v2; // rcx

  v1 = *(_QWORD *)(*(_QWORD *)(a1 + 64) + 16i64);
  v2 = *(void **)(v1 + 24);
  if ( v2 )
  {
    ExFreePool(v2);
    *(_QWORD *)(v1 + 24) = 0i64;
  }
  return 0i64;
}

//----- (0000000140005180) ----------------------------------------------------
NTSTATUS __fastcall sub_140005180(__int64 a1)
{
  __int64 v1; // rax
  struct _DEVICE_OBJECT *v2; // rdi
  __int64 v3; // rbx
  NTSTATUS result; // eax
  PVOID v5; // rcx
  NTSTATUS v6; // edi
  int v7[3]; // [rsp+40h] [rbp-28h] BYREF
  size_t Size; // [rsp+4Ch] [rbp-1Ch]

  v1 = *(_QWORD *)(a1 + 64);
  v2 = *(struct _DEVICE_OBJECT **)(v1 + 8);
  v3 = *(_QWORD *)(v1 + 16);
  result = sub_140005084(v2, 0x2A2014u, 0i64, 0, v7, 0x10u, 1u);
  if ( result >= 0 )
  {
    *(_DWORD *)(v3 + 8) = v7[1];
    *(_DWORD *)(v3 + 4) = v7[0];
    *(_DWORD *)(v3 + 12) = v7[2];
    *(_DWORD *)(v3 + 16) = Size;
    v5 = sub_140001870((unsigned int)Size);
    *(_QWORD *)(v3 + 24) = v5;
    if ( v5 )
    {
      v6 = sub_140005084(v2, 0x2A2018u, 0i64, 0, v5, *(_DWORD *)(v3 + 16), 1u);
      if ( v6 < 0 )
      {
        ExFreePool(*(PVOID *)(v3 + 24));
        *(_QWORD *)(v3 + 24) = 0i64;
      }
      return v6;
    }
    else
    {
      return -1073741801;
    }
  }
  return result;
}

//----- (0000000140005264) ----------------------------------------------------
__int64 __fastcall sub_140005264(__int64 a1, IRP *a2)
{
  __int64 v2; // rax
  struct _IO_STACK_LOCATION *CurrentStackLocation; // r14
  __int64 v5; // rbp
  struct _DEVICE_OBJECT *v6; // rdi
  UCHAR MinorFunction; // al
  int v9; // edi
  NTSTATUS v10; // eax

  v2 = *(_QWORD *)(a1 + 64);
  CurrentStackLocation = a2->Tail.Overlay.CurrentStackLocation;
  v5 = *(_QWORD *)(v2 + 16);
  v6 = *(struct _DEVICE_OBJECT **)(v2 + 8);
  MinorFunction = CurrentStackLocation->MinorFunction;
  switch ( MinorFunction )
  {
    case 0u:
      v9 = sub_140005398(v6, a2);
      if ( v9 < 0 )
      {
LABEL_17:
        IofCompleteRequest(a2, 0);
        return (unsigned int)v9;
      }
      v10 = sub_140005438(a1);
      a2->IoStatus.Status = v10;
LABEL_16:
      v9 = v10;
      goto LABEL_17;
    case 2u:
      if ( *(_BYTE *)(v5 + 48) )
      {
LABEL_12:
        a2->IoStatus.Status = 0;
        break;
      }
LABEL_11:
      sub_14000535C(a1);
      goto LABEL_12;
    case 4u:
      sub_1400054A0(a1);
      v10 = sub_140005398(v6, a2);
      *(_BYTE *)(v5 + 40) = 4;
      goto LABEL_16;
    case 9u:
      a2->IoStatus.Status = 0;
      v9 = sub_140005398(v6, a2);
      if ( v9 >= 0 )
        *(_DWORD *)(CurrentStackLocation->Parameters.WMI.ProviderId + 4) |= 0x200u;
      goto LABEL_17;
    case 0x17u:
      *(_BYTE *)(v5 + 40) = 5;
      *(_BYTE *)(v5 + 48) = 1;
      goto LABEL_11;
  }
  ++a2->CurrentLocation;
  ++a2->Tail.Overlay.CurrentStackLocation;
  return (unsigned int)IofCallDriver(v6, a2);
}

//----- (000000014000535C) ----------------------------------------------------
__int64 __fastcall sub_14000535C(__int64 a1)
{
  __int64 v2; // rdx
  __int64 v3; // rax
  int v4; // ecx

  v3 = *(_QWORD *)(a1 + 64);
  v2 = *(_QWORD *)(v3 + 16);
  LOBYTE(v3) = *(_BYTE *)(v2 + 40);
  if ( (unsigned __int8)v3 <= 7u )
  {
    v4 = 164;
    if ( _bittest(&v4, v3) )
    {
      *(_BYTE *)(v2 + 40) = 5;
      sub_140005000();
    }
  }
  return sub_140005154(a1);
}

//----- (0000000140005398) ----------------------------------------------------
__int64 __fastcall sub_140005398(PDEVICE_OBJECT DeviceObject, PIRP Irp)
{
  struct _IO_STACK_LOCATION *CurrentStackLocation; // rax
  struct _IO_STACK_LOCATION *v5; // rax
  struct _KEVENT Event; // [rsp+30h] [rbp-28h] BYREF

  KeInitializeEvent(&Event, SynchronizationEvent, 0);
  CurrentStackLocation = Irp->Tail.Overlay.CurrentStackLocation;
  *(_OWORD *)&CurrentStackLocation[-1].MajorFunction = *(_OWORD *)&CurrentStackLocation->MajorFunction;
  *(_OWORD *)&CurrentStackLocation[-1].Parameters.NotifyDirectoryEx.CompletionFilter = *(_OWORD *)&CurrentStackLocation->Parameters.NotifyDirectoryEx.CompletionFilter;
  *(_OWORD *)(&CurrentStackLocation[-1].Parameters.SetQuota + 6) = *(_OWORD *)(&CurrentStackLocation->Parameters.SetQuota
                                                                             + 6);
  CurrentStackLocation[-1].FileObject = CurrentStackLocation->FileObject;
  CurrentStackLocation[-1].Control = 0;
  v5 = Irp->Tail.Overlay.CurrentStackLocation;
  v5[-1].CompletionRoutine = (PIO_COMPLETION_ROUTINE)sub_1400018BC;
  v5[-1].Control = -32;
  v5[-1].Context = &Event;
  IofCallDriver(DeviceObject, Irp);
  KeWaitForSingleObject(&Event, Executive, 0, 0, 0i64);
  return (unsigned int)Irp->IoStatus.Status;
}

//----- (0000000140005438) ----------------------------------------------------
NTSTATUS __fastcall sub_140005438(__int64 a1)
{
  __int64 v2; // rsi
  NTSTATUS result; // eax
  char v4; // cl

  sub_140005008(a1);
  v2 = *(_QWORD *)(*(_QWORD *)(a1 + 64) + 16i64);
  *(_QWORD *)(v2 + 24) = 0i64;
  *(_DWORD *)(v2 + 16) = 0;
  *(_DWORD *)(v2 + 8) = 0;
  *(_DWORD *)(v2 + 4) = 0;
  *(_DWORD *)(v2 + 12) = 0;
  *(_BYTE *)(v2 + 40) = 0;
  result = sub_140005180(a1);
  v4 = 6;
  if ( !result )
    v4 = 2;
  *(_BYTE *)(v2 + 40) = v4;
  return result;
}

//----- (00000001400054A0) ----------------------------------------------------
__int64 __fastcall sub_1400054A0(__int64 a1)
{
  *(_BYTE *)(*(_QWORD *)(*(_QWORD *)(a1 + 64) + 16i64) + 40i64) = 3;
  sub_140005050(a1);
  sub_140005154(a1);
  return 0i64;
}

//----- (0000000140006000) ----------------------------------------------------
NTSTATUS __stdcall DriverEntry(_DRIVER_OBJECT *DriverObject, PUNICODE_STRING RegistryPath)
{
  struct _HID_MINIDRIVER_REGISTRATION MinidriverRegistration; // [rsp+20h] [rbp-38h] BYREF

  qmemcpy(&qword_140003050, "LGVirHid::", 10);
  sub_1400060D8();
  DriverObject->MajorFunction[15] = (PDRIVER_DISPATCH)sub_1400016F8;
  DriverObject->MajorFunction[27] = (PDRIVER_DISPATCH)sub_140005264;
  DriverObject->MajorFunction[22] = (PDRIVER_DISPATCH)sub_1400018DC;
  DriverObject->MajorFunction[23] = (PDRIVER_DISPATCH)sub_14000191C;
  DriverObject->DriverExtension->AddDevice = (PDRIVER_ADD_DEVICE)sub_140005028;
  MinidriverRegistration.Revision = 1;
  MinidriverRegistration.DriverObject = DriverObject;
  MinidriverRegistration.RegistryPath = RegistryPath;
  DriverObject->DriverUnload = (PDRIVER_UNLOAD)nullsub_1;
  MinidriverRegistration.DeviceExtensionSize = 56;
  MinidriverRegistration.DevicesArePolled = 0;
  return HidRegisterMinidriver(&MinidriverRegistration);
}
// 140003050: using guessed type __int64 qword_140003050;
// 140003058: using guessed type __int16 word_140003058;
// 14000504C: using guessed type __int64 __fastcall nullsub_1();

//----- (00000001400060D8) ----------------------------------------------------
char sub_1400060D8()
{
  char result; // al
  int v1; // [rsp+30h] [rbp+8h] BYREF

  v1 = 0;
  dword_140003040 = 0;
  result = sub_140001938(0, L"LGVirHid\\Parameters", L"DebugLevel", &v1);
  if ( result )
  {
    result = v1;
    dword_140003040 = v1;
  }
  return result;
}
// 140003040: using guessed type int dword_140003040;
// 1400061C0: using guessed type wchar_t aDebuglevel[11];
// 1400061E0: using guessed type wchar_t aLgvirhidParame[20];

// nfuncs=40 queued=28 decompiled=28 lumina nreq=0 worse=0 better=0
// ALL OK, 28 function(s) have been successfully decompiled
